### ISSUE TITLE
Add manual for using ibridges gui in desktop workspaces

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/vre-docs#39]
This shouldn't do what the ibridges documentation already does, but it can be as short as:
- Click Applications
- Configure, choose your template
- Add your UU email
- Copy your data password
- Then read the user docs

**Comment by dometto** [comment]
I had the same idea! I've asked @chStaiger to write this when she has time!

**Comment by dometto** [comment]
This should require tips about safely managing data access passwords.

**Comment by chStaiger** [comment]
@jelletreep @dometto I will create a draft!
